import 'package:flutter/material.dart';
import 'catalog.dart';
import 'calculations.dart';
import 'models/tool.dart';
import 'storage.dart';

void main() => runApp(const UtiliaApp());

class UtiliaApp extends StatefulWidget {
  const UtiliaApp({super.key});
  @override State<UtiliaApp> createState() => _UtiliaAppState();
}
class _UtiliaAppState extends State<UtiliaApp> {
  final storage = UtiliaStorage();
  bool darkMode = false;
  @override void initState() { super.initState(); _load(); }
  Future<void> _load() async { final v = await storage.loadDarkMode(); if (mounted) setState(() => darkMode = v); }
  Future<void> _theme(bool v) async { setState(() => darkMode = v); await storage.saveDarkMode(v); }
  @override Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false, title: 'UTILIA',
    themeMode: darkMode ? ThemeMode.dark : ThemeMode.light,
    theme: ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF167FF2)), scaffoldBackgroundColor: const Color(0xFFF7FAFD)),
    darkTheme: ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF167FF2), brightness: Brightness.dark)),
    home: HomePage(storage: storage, darkMode: darkMode, onTheme: _theme));
}

class HomePage extends StatefulWidget {
  const HomePage({super.key, required this.storage, required this.darkMode, required this.onTheme});
  final UtiliaStorage storage; final bool darkMode; final Future<void> Function(bool) onTheme;
  @override State<HomePage> createState() => _HomePageState();
}
class _HomePageState extends State<HomePage> {
  String query=''; int tab=0; Set<ToolType> favorites={}; List<Map<String,dynamic>> history=[];
  @override void initState(){super.initState();_load();}
  Future<void> _load() async { final f=await widget.storage.loadFavorites(); final h=await widget.storage.loadHistory(); if(mounted)setState((){favorites=f.map(_type).whereType<ToolType>().toSet();history=h;}); }
  ToolType? _type(String s){for(final t in ToolType.values){if(t.name==s)return t;}return null;}
  Future<void> _favorite(ToolType t) async { final n={...favorites}; n.contains(t)?n.remove(t):n.add(t); setState(()=>favorites=n); await widget.storage.saveFavorites(n.map((e)=>e.name).toSet()); }
  @override Widget build(BuildContext context){
    final filtered=tools.where((t)=>'${t.name} ${t.description} ${t.category}'.toLowerCase().contains(query.toLowerCase())).toList();
    return Scaffold(
      appBar:AppBar(title:const Text('UTILIA',style:TextStyle(fontWeight:FontWeight.w900,letterSpacing:1)),actions:[IconButton(onPressed:()=>showAboutDialog(context:context,applicationName:'UTILIA',applicationVersion:'0.3.0',applicationLegalese:'Pequeñas herramientas. Grandes soluciones.'),icon:const Icon(Icons.info_outline))]),
      body:tab==0?ListView(padding:const EdgeInsets.fromLTRB(16,4,16,24),children:[TextField(onChanged:(v)=>setState(()=>query=v),decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:'Buscar herramientas...',filled:true,fillColor:Theme.of(context).colorScheme.surface,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide.none))),const SizedBox(height:14),Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:const Color(0xFF167FF2),borderRadius:BorderRadius.circular(20)),child:const Text('Pequeñas herramientas.\nGrandes soluciones.',style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w800))),const SizedBox(height:20),Text(query.isEmpty?'Categorías':'Resultados (${filtered.length})',style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900)),const SizedBox(height:12),if(query.isEmpty)...categories.map((c)=>_categoryTile(context,c))else...filtered.map((t)=>_toolTile(context,t))]):tab==1?_favoritesView():tab==2?_historyView():_moreView(),
      bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Inicio'),NavigationDestination(icon:Icon(Icons.favorite_border),selectedIcon:Icon(Icons.favorite),label:'Favoritos'),NavigationDestination(icon:Icon(Icons.history),label:'Historial'),NavigationDestination(icon:Icon(Icons.apps),label:'Más')]),);
  }
  Widget _categoryTile(BuildContext c,String category){final list=tools.where((t)=>t.category==category).toList();final tint=categoryTints[category]!;return Card(elevation:0,margin:const EdgeInsets.only(bottom:10),child:ListTile(leading:CircleAvatar(backgroundColor:tint.withValues(alpha:.13),child:Icon(list.first.icon,color:tint)),title:Text(category,style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${list.length} herramientas'),trailing:const Icon(Icons.chevron_right_rounded),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>CategoryPage(category:category,tools:list,favorites:favorites,onFavorite:_favorite)))));}
  Widget _toolTile(BuildContext c,UtiliaTool t)=>Card(elevation:0,margin:const EdgeInsets.only(bottom:10),child:ListTile(leading:Icon(t.icon,color:t.tint),title:Text(t.name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(t.description),trailing:Icon(favorites.contains(t.type)?Icons.favorite:Icons.chevron_right_rounded),onTap:()=>openTool(c,t,widget.storage,_load),onLongPress:()=>_favorite(t.type)));
  Widget _favoritesView(){final list=tools.where((t)=>favorites.contains(t.type)).toList();return list.isEmpty?const Center(child:Text('Favoritos\nMantén pulsada una herramienta para añadirla.',textAlign:TextAlign.center)):ListView(padding:const EdgeInsets.all(16),children:list.map((t)=>_toolTile(context,t)).toList());}
  Widget _historyView()=>history.isEmpty?const Center(child:Text('Historial\nTus cálculos aparecerán aquí.',textAlign:TextAlign.center)):ListView(padding:const EdgeInsets.all(16),children:[Align(alignment:Alignment.centerRight,child:TextButton(onPressed:()async{await widget.storage.clearHistory();await _load();},child:const Text('Borrar historial'))),...history.map((h)=>Card(elevation:0,child:ListTile(leading:const Icon(Icons.calculate_outlined),title:Text('${h['tool']??'Cálculo'}'),subtitle:Text('${h['result']??''}'))))]);
  Widget _moreView()=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Preferencias',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:12),Card(elevation:0,child:SwitchListTile(title:const Text('Modo oscuro'),subtitle:const Text('Guardar preferencia en el dispositivo'),value:widget.darkMode,onChanged:widget.onTheme))]);
}

class CategoryPage extends StatelessWidget { const CategoryPage({super.key,required this.category,required this.tools,required this.favorites,required this.onFavorite}); final String category; final List<UtiliaTool> tools; final Set<ToolType> favorites; final Future<void> Function(ToolType) onFavorite; @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(category,style:const TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.all(16),children:tools.map((t)=>Card(elevation:0,margin:const EdgeInsets.only(bottom:10),child:ListTile(leading:Icon(t.icon,color:t.tint),title:Text(t.name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(t.description),trailing:Icon(favorites.contains(t.type)?Icons.favorite:Icons.chevron_right_rounded),onTap:()=>openTool(c,t,null,null),onLongPress:()=>onFavorite(t.type)))).toList())); }

void openTool(BuildContext c,UtiliaTool t,UtiliaStorage? storage,Future<void> Function()? refresh)=>Navigator.push(c,MaterialPageRoute(builder:(_)=>CalculatorPage(tool:t,storage:storage,onHistory:refresh)));

class CalculatorPage extends StatefulWidget { const CalculatorPage({super.key,required this.tool,this.storage,this.onHistory}); final UtiliaTool tool; final UtiliaStorage? storage; final Future<void> Function()? onHistory; @override State<CalculatorPage> createState()=>_CalculatorPageState(); }
class _CalculatorPageState extends State<CalculatorPage>{
 final controllers=List.generate(3,(_)=>TextEditingController()); double result=0; String unit='';
 @override void initState(){super.initState();controllers[0].text=widget.tool.type==ToolType.age||widget.tool.type==ToolType.dateDifference?'01/01/2000':'100';controllers[1].text=widget.tool.type==ToolType.iva?'21':'10';controllers[2].text='1';}
 @override void dispose(){for(final c in controllers)c.dispose();super.dispose();}
 List<String> get labels{switch(widget.tool.type){case ToolType.age:return['Fecha de nacimiento (dd/mm/aaaa)',''];case ToolType.dateDifference:return['Fecha inicial (dd/mm/aaaa)','Fecha final (dd/mm/aaaa)'];case ToolType.workHours:return['Hora inicio (ej. 8,5)','Hora fin (ej. 17)','Descanso (min)'];case ToolType.countdown:return['Horas','Minutos','Segundos'];case ToolType.length:return['Valor','Unidad origen (mm/cm/m/km/in/ft/yd/mi)','Unidad destino'];case ToolType.weight:return['Valor','Unidad origen (mg/g/kg/t/oz/lb)','Unidad destino'];case ToolType.bmi:return['Peso (kg)','Altura (cm)'];case ToolType.fuel:return['Distancia (km)','Consumo (L/100 km)','Precio €/L'];case ToolType.tip:return['Cuenta (€)','Propina (%)','Personas'];case ToolType.loan:return['Capital (€)','Interés anual (%)','Meses'];case ToolType.compoundInterest:return['Capital (€)','Interés anual (%)','Años'];case ToolType.area:return['Largo (m)','Ancho (m)'];case ToolType.paint:return['Superficie (m²)','Cobertura (m²/L)'];case ToolType.electricity:return['Potencia (W)','Horas/día','Días'];case ToolType.costPerKm:return['Coste total (€)','Kilómetros'];case ToolType.gradeAverage:return['Notas separadas por comas',''];case ToolType.ruleOfThree:return['A','B','C'];default:return['Cantidad','Porcentaje (%)'];}}
 DateTime? _date(String s){final p=s.trim().split('/');if(p.length!=3)return null;final d=int.tryParse(p[0]),m=int.tryParse(p[1]),y=int.tryParse(p[2]);if(d==null||m==null||y==null)return null;final v=DateTime(y,m,d);return v.day==d&&v.month==m&&v.year==y?v:null;}
 void calculate(){final x=parseNumber(controllers[0].text),y=parseNumber(controllers[1].text),z=parseNumber(controllers[2].text);double r;String u='';switch(widget.tool.type){case ToolType.percentage:r=percentageOf(x,y);break;case ToolType.discount:r=discountedPrice(x,y);break;case ToolType.iva:r=priceWithIva(x,y);break;case ToolType.tip:r=tipPerPerson(x,y,z.toInt());break;case ToolType.loan:r=loanPayment(x,y,z.toInt());break;case ToolType.compoundInterest:r=compound(x,y,z.toInt());break;case ToolType.area:r=area(x,y);u='m²';break;case ToolType.paint:r=paintLitres(x,y);u='L';break;case ToolType.electricity:r=electricityCost(x,y,z,.20);u='€';break;case ToolType.fuel:r=fuelCost(x,y,z);u='€';break;case ToolType.costPerKm:r=costPerKm(x,y);u='€/km';break;case ToolType.bmi:r=bmi(x,y);break;case ToolType.gradeAverage:r=gradeAverage(controllers[0].text.split(',').map(parseNumber).toList());break;case ToolType.ruleOfThree:r=ruleOfThree(x,y,z);break;case ToolType.age:final d=_date(controllers[0].text);if(d==null){_error('Usa una fecha válida: dd/mm/aaaa');return;}r=ageInYears(d);u='años';break;case ToolType.dateDifference:final a=_date(controllers[0].text),b=_date(controllers[1].text);if(a==null||b==null){_error('Usa fechas válidas: dd/mm/aaaa');return;}r=dateDifferenceDays(a,b).toDouble();u='días';break;case ToolType.workHours:r=workHours(x,y,z);u='h';break;case ToolType.countdown:r=countdownSeconds(x.toInt(),y.toInt(),z.toInt()).toDouble();u='seg';break;case ToolType.length:r=convertLength(x,controllers[1].text.trim().toLowerCase(),controllers[2].text.trim().toLowerCase());u=controllers[2].text.trim();break;case ToolType.weight:r=convertWeight(x,controllers[1].text.trim().toLowerCase(),controllers[2].text.trim().toLowerCase());u=controllers[2].text.trim();break;}setState((){result=r;unit=u;});widget.storage?.addHistory({'tool':widget.tool.name,'result':'${r.toStringAsFixed(2).replaceAll('.',',')} $u','timestamp':DateTime.now().toIso8601String()});widget.onHistory?.call();}
 void _error(String m)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(m)));
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(widget.tool.name,style:const TextStyle(fontWeight:FontWeight.w900))),body:ListView(padding:const EdgeInsets.all(18),children:[Text(widget.tool.description,style:const TextStyle(color:Color(0xFF52606D))),const SizedBox(height:22),for(var i=0;i<labels.length;i++)if(labels[i].isNotEmpty)Padding(padding:const EdgeInsets.only(bottom:14),child:TextField(controller:controllers[i],keyboardType:TextInputType.text,decoration:InputDecoration(labelText:labels[i],filled:true,border:const OutlineInputBorder(borderSide:BorderSide.none)))),FilledButton(onPressed:calculate,child:const Text('Calcular')),const SizedBox(height:18),Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:const Color(0xFFE7F8F2),borderRadius:BorderRadius.circular(20)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Resultado',style:TextStyle(fontWeight:FontWeight.w800)),Text('${result.toStringAsFixed(2).replaceAll('.',',')} $unit',style:const TextStyle(fontSize:34,fontWeight:FontWeight.w900))]))]));
}
